language: php

php:
  - 7.0

before_script:
    - composer self-update
    - composer install --dev --no-interaction --prefer-source

script:
    - bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)